packages:
  - "apps/*"
  - "packages/*"
  - "tooling/*"
allowBuilds:
  esbuild: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1124.0'
  - '@aws-sdk/credential-provider-node@3.972.82'
  - '@aws-sdk/s3-request-presigner@3.1124.0'
